<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->countries()
            ->filter(fn ($country) => app()->isProduction() || ! app()->isProduction() && $country[0] === 'United Kingdom')
            ->each(function ($country, $code) {
                Country::updateOrCreate(
                    [
                        'code' => $code,
                    ],
                    [
                        'name' => $country[0],
                        'prefix' => $country[1],
                    ],
                );
            });
    }

    private function countries(): Collection
    {
        return collect([
            'AF' => ['Afghanistan', 93, 'AFN'],
            'AX' => ['Åland Islands', 358, 'EUR'],
            'AL' => ['Albania', 355, 'ALL'],
            'DZ' => ['Algeria', 213, 'DZD'],
            'AS' => ['American Samoa', 1684, 'USD'],
            'AD' => ['Andorra', 376, 'EUR'],
            'AO' => ['Angola', 244, 'AOA'],
            'AI' => ['Anguilla', 1264, 'XCD'],
            'AQ' => ['Antarctica', null, 'AAD'],
            'AG' => ['Antigua and Barbuda', 1268, 'XCD'],
            'AR' => ['Argentina', 54, 'ARS'],
            'AM' => ['Armenia', 374, 'AMD'],
            'AW' => ['Aruba', 297, 'AWG'],
            'AU' => ['Australia', 61, 'AUD'],
            'AT' => ['Austria', 43, 'EUR'],
            'AZ' => ['Azerbaijan', 994, 'AZN'],
            'BS' => ['Bahamas', 1242, 'BSD'],
            'BH' => ['Bahrain', 973, 'BHD'],
            'BD' => ['Bangladesh', 880, 'BDT'],
            'BB' => ['Barbados', 1246, 'BBD'],
            'BY' => ['Belarus', 375, 'BYN'],
            'BE' => ['Belgium', 32, 'EUR'],
            'BZ' => ['Belize', 501, 'BZD'],
            'BJ' => ['Benin', 229, 'XOF'],
            'BM' => ['Bermuda', 1441, 'BMD'],
            'BT' => ['Bhutan', 975, 'BTN'],
            'BO' => ['Bolivia', 591, 'BOB'],
            'BQ' => ['Bonaire, Sint Eustatius and Saba', 599, 'USD'],
            'BA' => ['Bosnia and Herzegovina', 387, 'BAM'],
            'BW' => ['Botswana', 267, 'BWP'],
            'BV' => ['Bouvet Island', null, 'NOK'],
            'BR' => ['Brazil', 55, 'BRL'],
            'IO' => ['British Indian Ocean Territory', 246, 'USD'],
            'BN' => ['Brunei Darussalam', 673, 'BND'],
            'BG' => ['Bulgaria', 359, 'BGN'],
            'BF' => ['Burkina Faso', 226, 'XOF'],
            'BI' => ['Burundi', 257, 'BIF'],
            'KH' => ['Cambodia', 855, 'KHR'],
            'CM' => ['Cameroon', 237, 'XAF'],
            'CA' => ['Canada', 1, 'CAD'],
            'CV' => ['Cabo Verde', 238, 'CVE'],
            'KY' => ['Cayman Islands', 1345, 'KYD'],
            'CF' => ['Central African Republic', 236, 'XAF'],
            'TD' => ['Chad', 235, 'XAF'],
            'CL' => ['Chile', 56, 'CLP'],
            'CN' => ['China', 86, 'CNY'],
            'CX' => ['Christmas Island', 61, 'AUD'],
            'CC' => ['Cocos (Keeling) Islands', 61, 'AUD'],
            'CO' => ['Colombia', 57, 'COP'],
            'KM' => ['Comoros', 269, 'KMF'],
            'CG' => ['Congo', 242, 'XAF'],
            'CD' => ['Congo (Democratic Republic of the)', 243, 'CDF'],
            'CK' => ['Cook Islands', 682, 'NZD'],
            'CR' => ['Costa Rica', 506, 'CRC'],
            'CI' => ["Côte d'Ivoire", 225, 'XOF'],
            'HR' => ['Croatia', 385, 'HRK'],
            'CU' => ['Cuba', 53, 'CUP'],
            'CW' => ['Curaçao', 599, 'ANG'],
            'CY' => ['Cyprus', 357, 'EUR'],
            'CZ' => ['Czech Republic', 420, 'CZK'],
            'DK' => ['Denmark', 45, 'DKK'],
            'DJ' => ['Djibouti', 253, 'DJF'],
            'DM' => ['Dominica', 1767, 'XCD'],
            'DO' => ['Dominican Republic', 1, 'DOP'],
            'EC' => ['Ecuador', 593, 'USD'],
            'EG' => ['Egypt', 20, 'EGP'],
            'SV' => ['El Salvador', 503, 'USD'],
            'GQ' => ['Equatorial Guinea', 240, 'XAF'],
            'ER' => ['Eritrea', 291, 'ERN'],
            'EE' => ['Estonia', 372, 'EUR'],
            'ET' => ['Ethiopia', 251, 'ETB'],
            'FK' => ['Falkland Islands (Malvinas)', 500, 'FKP'],
            'FO' => ['Faroe Islands', 298, 'DKK'],
            'FJ' => ['Fiji', 679, 'FJD'],
            'FI' => ['Finland', 358, 'EUR'],
            'FR' => ['France', 33, 'EUR'],
            'GF' => ['French Guiana', 594, 'EUR'],
            'PF' => ['French Polynesia', 689, 'XPF'],
            'TF' => ['French Southern Territories', null, 'EUR'],
            'GA' => ['Gabon', 241, 'XAF'],
            'GM' => ['Gambia', 220, 'GMD'],
            'GE' => ['Georgia', 995, 'GEL'],
            'DE' => ['Germany', 49, 'EUR'],
            'GH' => ['Ghana', 233, 'GHS'],
            'GI' => ['Gibraltar', 350, 'GIP'],
            'GR' => ['Greece', 30, 'EUR'],
            'GL' => ['Greenland', 299, 'DKK'],
            'GD' => ['Grenada', 1473, 'XCD'],
            'GP' => ['Guadeloupe', 590, 'EUR'],
            'GU' => ['Guam', 1671, 'USD'],
            'GT' => ['Guatemala', 502, 'GTQ'],
            'GG' => ['Guernsey', 1, 'GBP'],
            'GN' => ['Guinea', 224, 'GNF'],
            'GW' => ['Guinea-Bissau', 245, 'XOF'],
            'GY' => ['Guyana', 592, 'GYD'],
            'HT' => ['Haiti', 509, 'HTG'],
            'HM' => ['Heard Island and McDonald Islands', null, 'AUD'],
            'HN' => ['Honduras', 504, 'HNL'],
            'HK' => ['Hong Kong', 852, 'HKD'],
            'HU' => ['Hungary', 36, 'HUF'],
            'IS' => ['Iceland', 354, 'ISK'],
            'IN' => ['India', 91, 'INR'],
            'ID' => ['Indonesia', 62, 'IDR'],
            'IR' => ['Iran (Islamic Republic of)', 98, 'IRR'],
            'IQ' => ['Iraq', 964, 'IQD'],
            'IE' => ['Ireland', 353, 'EUR'],
            'IM' => ['Isle of Man', 44, 'GBP'],
            'IL' => ['Israel', 972, 'ILS'],
            'IT' => ['Italy', 39, 'EUR'],
            'JM' => ['Jamaica', 1876, 'JMD'],
            'JP' => ['Japan', 81, 'JPY'],
            'JE' => ['Jersey', 44, 'GBP'],
            'JO' => ['Jordan', 962, 'JOD'],
            'KZ' => ['Kazakhstan', 7, 'KZT'],
            'KE' => ['Kenya', 254, 'KES'],
            'KI' => ['Kiribati', 686, 'AUD'],
            'KW' => ['Kuwait', 965, 'KWD'],
            'KG' => ['Kyrgyzstan', 996, 'KGS'],
            'LA' => ["Lao People's Democratic Republic", 856, 'LAK'],
            'LV' => ['Latvia', 371, 'EUR'],
            'LB' => ['Lebanon', 961, 'LBP'],
            'LS' => ['Lesotho', 266, 'LSL'],
            'LR' => ['Liberia', 231, 'LRD'],
            'LY' => ['Libya', 218, 'LYD'],
            'LI' => ['Liechtenstein', 423, 'CHF'],
            'LT' => ['Lithuania', 370, 'EUR'],
            'LU' => ['Luxembourg', 352, 'EUR'],
            'MO' => ['Macao', 853, 'MOP'],
            'MK' => ['Macedonia (the former Yugoslav Republic of)', 389, 'MKD'],
            'MG' => ['Madagascar', 261, 'MGA'],
            'MW' => ['Malawi', 265, 'MWK'],
            'MY' => ['Malaysia', 60, 'MYR'],
            'MV' => ['Maldives', 960, 'MVR'],
            'ML' => ['Mali', 223, 'XOF'],
            'MT' => ['Malta', 356, 'EUR'],
            'MH' => ['Marshall Islands', 692, 'USD'],
            'MQ' => ['Martinique', 596, 'EUR'],
            'MR' => ['Mauritania', 222, 'MRO'],
            'MU' => ['Mauritius', 230, 'MUR'],
            'YT' => ['Mayotte', 262, 'EUR'],
            'MX' => ['Mexico', 52, 'MXN'],
            'FM' => ['Micronesia (Federated States of)', 691, 'USD'],
            'MD' => ['Moldova (Republic of)', 373, 'MDL'],
            'MC' => ['Monaco', 377, 'EUR'],
            'MN' => ['Mongolia', 976, 'MNT'],
            'ME' => ['Montenegro', 382, 'EUR'],
            'MS' => ['Montserrat', 1664, 'XCD'],
            'MA' => ['Morocco', 212, 'MAD'],
            'MZ' => ['Mozambique', 258, 'MZN'],
            'MM' => ['Myanmar', 95, 'MMK'],
            'NA' => ['Namibia', 264, 'NAD'],
            'NR' => ['Nauru', 674, 'AUD'],
            'NP' => ['Nepal', 977, 'NPR'],
            'NL' => ['Netherlands', 31, 'EUR'],
            'NC' => ['New Caledonia', 687, 'XPF'],
            'NZ' => ['New Zealand', 64, 'NZD'],
            'NI' => ['Nicaragua', 505, 'NIO'],
            'NE' => ['Niger', 227, 'XOF'],
            'NG' => ['Nigeria', 234, 'NGN'],
            'NU' => ['Niue', 683, 'NZD'],
            'NF' => ['Norfolk Island', 672, 'AUD'],
            'KP' => ['North Korea', 850, 'KPW'],
            'MP' => ['Northern Mariana Islands', 1670, 'USD'],
            'NO' => ['Norway', 47, 'NOK'],
            'OM' => ['Oman', 968, 'OMR'],
            'PK' => ['Pakistan', 92, 'PKR'],
            'PW' => ['Palau', 680, 'USD'],
            'PS' => ['Palestine, State of', 970, 'IRL'],
            'PA' => ['Panama', 507, 'PAB'],
            'PG' => ['Papua New Guinea', 675, 'PGK'],
            'PY' => ['Paraguay', 595, 'PYG'],
            'PE' => ['Peru', 51, 'PEN'],
            'PH' => ['Philippines', 63, 'PHP'],
            'PN' => ['Pitcairn', null, 'NZD'],
            'PL' => ['Poland', 48, 'PLN'],
            'PT' => ['Portugal', 351, 'EUR'],
            'PR' => ['Puerto Rico', 1, 'USD'],
            'QA' => ['Qatar', 974, 'QAR'],
            'XK' => ['Republic of Kosovo', 383, 'EUR'],
            'RE' => ['Réunion', 262, 'EUR'],
            'RO' => ['Romania', 40, 'RON'],
            'RU' => ['Russian Federation', 7, 'RUB'],
            'RW' => ['Rwanda', 250, 'RWF'],
            'BL' => ['Saint Barthélemy', 590, 'EUR'],
            'SH' => ['Saint Helena, Ascension and Tristan da Cunha', 290, 'SHP'],
            'KN' => ['Saint Kitts and Nevis', 1869, 'XCD'],
            'LC' => ['Saint Lucia', 1758, 'XCD'],
            'MF' => ['Saint Martin (French part)', 590, 'EUR'],
            'PM' => ['Saint Pierre and Miquelon', 508, 'EUR'],
            'VC' => ['Saint Vincent and the Grenadines', 1784, 'XCD'],
            'WS' => ['Samoa', 685, 'WST'],
            'SM' => ['San Marino', 378, 'EUR'],
            'ST' => ['Sao Tome and Principe', 239, 'STD'],
            'SA' => ['Saudi Arabia', 966, 'SAR'],
            'SN' => ['Senegal', 221, 'XOF'],
            'RS' => ['Serbia', 381, 'RSD'],
            'SC' => ['Seychelles', 248, 'SCR'],
            'SL' => ['Sierra Leone', 232, 'SLL'],
            'SG' => ['Singapore', 65, 'SGD'],
            'SX' => ['Sint Maarten (Dutch part)', 1721, 'ANG'],
            'SK' => ['Slovakia', 421, 'EUR'],
            'SI' => ['Slovenia', 386, 'EUR'],
            'SB' => ['Solomon Islands', 677, 'SBD'],
            'SO' => ['Somalia', 252, 'SOS'],
            'ZA' => ['South Africa', 27, 'ZAR'],
            'GS' => ['South Georgia and the South Sandwich Islands', null, 'GBP'],
            'KR' => ['South Korea', 82, 'KRW'],
            'SS' => ['South Sudan', 211, 'SSP'],
            'ES' => ['Spain', 34, 'EUR'],
            'LK' => ['Sri Lanka', 94, 'LKR'],
            'SD' => ['Sudan', 249, 'SDG'],
            'SR' => ['Suriname', 597, 'SRD'],
            'SJ' => ['Svalbard and Jan Mayen', 47, 'NOK'],
            'SZ' => ['Swaziland', 268, 'SZL'],
            'SE' => ['Sweden', 46, 'SEK'],
            'CH' => ['Switzerland', 41, 'CHF'],
            'SY' => ['Syria', 963, 'SYP'],
            'TW' => ['Taiwan', 886, 'TWD'],
            'TJ' => ['Tajikistan', 992, 'TJS'],
            'TZ' => ['Tanzania', 255, 'TZS'],
            'TH' => ['Thailand', 66, 'THB'],
            'TL' => ['Timor-Leste', 670, 'USD'],
            'TG' => ['Togo', 228, 'XOF'],
            'TK' => ['Tokelau', 690, 'NZD'],
            'TO' => ['Tonga', 676, 'TOP'],
            'TT' => ['Trinidad and Tobago', 1868, 'TTD'],
            'TN' => ['Tunisia', 216, 'TND'],
            'TR' => ['Turkey', 90, 'TRY'],
            'TM' => ['Turkmenistan', 993, 'TMT'],
            'TC' => ['Turks and Caicos Islands', 1649, 'USD'],
            'TV' => ['Tuvalu', 688, 'AUD'],
            'UG' => ['Uganda', 256, 'UGX'],
            'UA' => ['Ukraine', 380, 'UAH'],
            'AE' => ['United Arab Emirates', 971, 'AED'],
            'GB' => ['United Kingdom', 44, 'GBP'],
            'US' => ['United States of America', 1, 'USD'],
            'UM' => ['United States Minor Outlying Islands', null, 'USD'],
            'UY' => ['Uruguay', 598, 'UYU'],
            'UZ' => ['Uzbekistan', 998, 'UZS'],
            'VU' => ['Vanuatu', 678, 'VUV'],
            'VA' => ['Vatican City State (Holy See)', 39, 'EUR'],
            'VE' => ['Venezuela', 58, 'VEF'],
            'VN' => ['Vietnam', 84, 'VND'],
            'VG' => ['Virgin Islands (British)', 1284, 'USD'],
            'VI' => ['Virgin Islands (U.S.)', 1340, 'USD'],
            'WF' => ['Wallis and Futuna Islands', 681, 'XPF'],
            'EH' => ['Western Sahara', 212, 'MAD'],
            'YE' => ['Yemen', 967, 'YER'],
            'ZM' => ['Zambia', 260, 'ZMW'],
            'ZW' => ['Zimbabwe', 263, 'ZWL'],
        ]);
    }
}
