import { defineConfig } from 'oxlint'
import autoImports from './.eslintrc-auto-import.json' with { type: 'json' }

export default defineConfig({
    plugins: ['jsdoc', 'typescript', 'vue', 'vitest'],
    categories: {
        correctness: 'warn',
    },
    env: {
        builtin: true,
    },
    rules: {
        'vue/no-arrow-functions-in-watch': 'error',
        'vue/no-deprecated-destroyed-lifecycle': 'error',
        'vue/no-export-in-script-setup': 'error',
        'vue/no-lifecycle-after-await': 'error',
        'vue/prefer-import-from-vue': 'error',
        'vue/valid-define-emits': 'error',
        'vue/valid-define-props': 'error',
        'vue/no-multiple-slot-args': 'warn',
        'vue/no-required-prop-with-default': 'warn',
        '@typescript-eslint/ban-ts-comment': 'error',
        'no-array-constructor': 'error',
        '@typescript-eslint/no-duplicate-enum-values': 'error',
        '@typescript-eslint/no-empty-object-type': 'warn',
        '@typescript-eslint/no-extra-non-null-assertion': 'error',
        '@typescript-eslint/no-misused-new': 'error',
        '@typescript-eslint/no-namespace': 'error',
        '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
        '@typescript-eslint/no-require-imports': 'error',
        '@typescript-eslint/no-this-alias': 'error',
        '@typescript-eslint/no-unnecessary-type-constraint': 'error',
        '@typescript-eslint/no-unsafe-declaration-merging': 'error',
        '@typescript-eslint/no-unsafe-function-type': 'error',
        'no-unused-expressions': 'error',
        'no-unused-vars': 'error',
        '@typescript-eslint/no-wrapper-object-types': 'error',
        '@typescript-eslint/prefer-as-const': 'error',
        '@typescript-eslint/prefer-namespace-keyword': 'error',
        '@typescript-eslint/triple-slash-reference': 'error',
        'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
    ...autoImports,
    overrides: [
        {
            files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts', '**/*.vue'],
            rules: {
                'constructor-super': 'off',
                'no-class-assign': 'off',
                'no-const-assign': 'off',
                'no-dupe-class-members': 'off',
                'no-dupe-keys': 'off',
                'no-func-assign': 'off',
                'no-import-assign': 'off',
                'no-new-native-nonconstructor': 'off',
                'no-obj-calls': 'off',
                'no-redeclare': 'off',
                'no-setter-return': 'off',
                'no-this-before-super': 'off',
                'no-unsafe-negation': 'off',
                'no-var': 'error',
                'no-with': 'off',
                'prefer-const': 'error',
                'prefer-rest-params': 'error',
                'prefer-spread': 'error',
            },
        },
    ],
    ignorePatterns: [
        'vendor',
        'node_modules',
        'public',
        'bootstrap/ssr',
        'tailwind.config.js',
        'packages',
        'resources/js/plugin/lararail/**.ts',
        'resources/js/routes/routes.json',
        'resources/js/types/auto-components.d.ts',
        'resources/js/types/auto-imports.d.ts',
        'resources/js/types/routes.d.ts',
    ],
})
