[PHP]
post_max_size = 100M
upload_max_filesize = 100M
memory_limit = 1024M
variables_order = EGPCS
short_open_tag = 0
error_reporting = E_ALL
display_startup_errors = On
display_errors = On
pcov.directory = .
error_log=/var/www/html/storage/logs/php_errors.log

[Date]
date.timezone = UTC
