#!/bin/bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

if [ ! -z "$BRANCH_NAME" ] && [ "$BRANCH_NAME" != "HEAD" ] && [ "$SKIP_PREPARE_COMMIT_MSG" != 1 ]; then
    PREFIX_PATTERN='([A-Za-z]+-[0-9]+)'

    [[ $BRANCH_NAME =~ $PREFIX_PATTERN ]]

    PREFIX=${BASH_REMATCH[1]^^}

    PREFIX_IN_COMMIT=$(grep -c "\[$PREFIX\]" $1)

    # Ensure PREFIX exists in BRANCH_NAME and is not already present in the commit message
    if [[ -n "$PREFIX" ]] && ! [[ $PREFIX_IN_COMMIT -ge 1 ]]; then
        sed -i.bak -e "1s~^~[$PREFIX] ~" $1 #prefix
    fi
fi
