name: Type coverage

permissions:
  contents: read

on:
  push:
    branches:
      - master
    paths:
      - "**.php"
      - "composer.lock"
      - ".github/workflows/coverage.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**.php"
      - "composer.lock"
      - ".github/workflows/coverage.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-coverage:
    name: Type Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/setup-php

      - uses: ./.github/actions/setup-project

      - uses: ./.github/actions/setup-composer

      - uses: ./.github/actions/validate-composer

      - uses: ./.github/actions/setup-migrations

      - name: Run Type Coverage
        run: composer test:type-coverage
